// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqAjToYTqqAwQZUYbkEWC5jFu3_107i4',
    appId: '1:834007746519:web:c918d0547ffa9063202d92',
    messagingSenderId: '834007746519',
    projectId: 'taxiapp-6761d',
    authDomain: 'taxiapp-6761d.firebaseapp.com',
    databaseURL: 'https://taxiapp-6761d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxiapp-6761d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLeidsGKkCyrjqMobClu-X737-R-6iLdw',
    appId: '1:834007746519:android:d58cf0222818cc03202d92',
    messagingSenderId: '834007746519',
    projectId: 'taxiapp-6761d',
    databaseURL: 'https://taxiapp-6761d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxiapp-6761d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ysYcd-j_aDhuhin4is5FfbbObm-g8uw',
    appId: '1:834007746519:ios:bcd6b98918777bb5202d92',
    messagingSenderId: '834007746519',
    projectId: 'taxiapp-6761d',
    databaseURL: 'https://taxiapp-6761d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxiapp-6761d.firebasestorage.app',
    iosBundleId: 'com.example.driverTaxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ysYcd-j_aDhuhin4is5FfbbObm-g8uw',
    appId: '1:834007746519:ios:bcd6b98918777bb5202d92',
    messagingSenderId: '834007746519',
    projectId: 'taxiapp-6761d',
    databaseURL: 'https://taxiapp-6761d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxiapp-6761d.firebasestorage.app',
    iosBundleId: 'com.example.driverTaxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwqAjToYTqqAwQZUYbkEWC5jFu3_107i4',
    appId: '1:834007746519:web:fe6a6be1b986919f202d92',
    messagingSenderId: '834007746519',
    projectId: 'taxiapp-6761d',
    authDomain: 'taxiapp-6761d.firebaseapp.com',
    databaseURL: 'https://taxiapp-6761d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxiapp-6761d.firebasestorage.app',
  );
}
