// Mocks generated by Mockito 5.4.4 from annotations
// in driver_taxi_app/test/driver_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:driver_taxi_app/auth/cubit/auth_cubit.dart' as _i6;
import 'package:driver_taxi_app/auth/cubit/auth_state.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:reown_appkit/reown_appkit.dart' as _i2;
import 'package:reown_core/store/i_generic_store.dart' as _i5;
import 'package:shared/models/car_type.dart' as _i8;
import 'package:shared/repositories/driver/driver_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReownAppKit_0 extends _i1.SmartFake implements _i2.ReownAppKit {
  _FakeReownAppKit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriverRepository_1 extends _i1.SmartFake
    implements _i3.DriverRepository {
  _FakeDriverRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriverAuthState_2 extends _i1.SmartFake
    implements _i4.DriverAuthState {
  _FakeDriverAuthState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIReownCore_3 extends _i1.SmartFake implements _i2.IReownCore {
  _FakeIReownCore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePairingMetadata_4 extends _i1.SmartFake
    implements _i2.PairingMetadata {
  _FakePairingMetadata_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIReownSign_5 extends _i1.SmartFake implements _i2.IReownSign {
  _FakeIReownSign_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_6<T extends _i2.EventArgs> extends _i1.SmartFake
    implements _i2.Event<T> {
  _FakeEvent_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIGenericStore_7<T> extends _i1.SmartFake
    implements _i5.IGenericStore<T> {
  _FakeIGenericStore_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeISessions_8 extends _i1.SmartFake implements _i2.ISessions {
  _FakeISessions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIPairingStore_9 extends _i1.SmartFake implements _i2.IPairingStore {
  _FakeIPairingStore_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectResponse_10 extends _i1.SmartFake
    implements _i2.ConnectResponse {
  _FakeConnectResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionAuthRequestResponse_11 extends _i1.SmartFake
    implements _i2.SessionAuthRequestResponse {
  _FakeSessionAuthRequestResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriverAuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverAuthCubit extends _i1.Mock implements _i6.DriverAuthCubit {
  @override
  _i2.ReownAppKit get appKit => (super.noSuchMethod(
        Invocation.getter(#appKit),
        returnValue: _FakeReownAppKit_0(
          this,
          Invocation.getter(#appKit),
        ),
        returnValueForMissingStub: _FakeReownAppKit_0(
          this,
          Invocation.getter(#appKit),
        ),
      ) as _i2.ReownAppKit);

  @override
  set appKit(_i2.ReownAppKit? _appKit) => super.noSuchMethod(
        Invocation.setter(
          #appKit,
          _appKit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DriverRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDriverRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDriverRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.DriverRepository);

  @override
  _i4.DriverAuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDriverAuthState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDriverAuthState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.DriverAuthState);

  @override
  _i7.Stream<_i4.DriverAuthState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i4.DriverAuthState>.empty(),
        returnValueForMissingStub: _i7.Stream<_i4.DriverAuthState>.empty(),
      ) as _i7.Stream<_i4.DriverAuthState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void isConnected(_i2.ReownAppKitModal? modal) => super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [modal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> createAccount(
    String? id,
    String? firstName,
    String? lastName,
    String? carName,
    _i8.CarType? carType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [
            id,
            firstName,
            lastName,
            carName,
            carType,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateAccount(
    String? id,
    String? firstName,
    String? lastName,
    String? carName,
    _i8.CarType? carType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [
            id,
            firstName,
            lastName,
            carName,
            carType,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void emit(_i4.DriverAuthState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i4.DriverAuthState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ReownAppKit].
///
/// See the documentation for Mockito's code generation for more information.
class MockReownAppKit extends _i1.Mock implements _i2.ReownAppKit {
  @override
  String get protocol => (super.noSuchMethod(
        Invocation.getter(#protocol),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#protocol),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#protocol),
        ),
      ) as String);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i2.IReownCore get core => (super.noSuchMethod(
        Invocation.getter(#core),
        returnValue: _FakeIReownCore_3(
          this,
          Invocation.getter(#core),
        ),
        returnValueForMissingStub: _FakeIReownCore_3(
          this,
          Invocation.getter(#core),
        ),
      ) as _i2.IReownCore);

  @override
  _i2.PairingMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakePairingMetadata_4(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakePairingMetadata_4(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.PairingMetadata);

  @override
  _i2.IReownSign get reOwnSign => (super.noSuchMethod(
        Invocation.getter(#reOwnSign),
        returnValue: _FakeIReownSign_5(
          this,
          Invocation.getter(#reOwnSign),
        ),
        returnValueForMissingStub: _FakeIReownSign_5(
          this,
          Invocation.getter(#reOwnSign),
        ),
      ) as _i2.IReownSign);

  @override
  set reOwnSign(_i2.IReownSign? _reOwnSign) => super.noSuchMethod(
        Invocation.setter(
          #reOwnSign,
          _reOwnSign,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Event<_i2.SessionConnect> get onSessionConnect => (super.noSuchMethod(
        Invocation.getter(#onSessionConnect),
        returnValue: _FakeEvent_6<_i2.SessionConnect>(
          this,
          Invocation.getter(#onSessionConnect),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionConnect>(
          this,
          Invocation.getter(#onSessionConnect),
        ),
      ) as _i2.Event<_i2.SessionConnect>);

  @override
  _i2.Event<_i2.SessionEvent> get onSessionEvent => (super.noSuchMethod(
        Invocation.getter(#onSessionEvent),
        returnValue: _FakeEvent_6<_i2.SessionEvent>(
          this,
          Invocation.getter(#onSessionEvent),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionEvent>(
          this,
          Invocation.getter(#onSessionEvent),
        ),
      ) as _i2.Event<_i2.SessionEvent>);

  @override
  _i2.Event<_i2.SessionExpire> get onSessionExpire => (super.noSuchMethod(
        Invocation.getter(#onSessionExpire),
        returnValue: _FakeEvent_6<_i2.SessionExpire>(
          this,
          Invocation.getter(#onSessionExpire),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionExpire>(
          this,
          Invocation.getter(#onSessionExpire),
        ),
      ) as _i2.Event<_i2.SessionExpire>);

  @override
  _i2.Event<_i2.SessionProposalEvent> get onProposalExpire =>
      (super.noSuchMethod(
        Invocation.getter(#onProposalExpire),
        returnValue: _FakeEvent_6<_i2.SessionProposalEvent>(
          this,
          Invocation.getter(#onProposalExpire),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionProposalEvent>(
          this,
          Invocation.getter(#onProposalExpire),
        ),
      ) as _i2.Event<_i2.SessionProposalEvent>);

  @override
  _i2.Event<_i2.SessionExtend> get onSessionExtend => (super.noSuchMethod(
        Invocation.getter(#onSessionExtend),
        returnValue: _FakeEvent_6<_i2.SessionExtend>(
          this,
          Invocation.getter(#onSessionExtend),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionExtend>(
          this,
          Invocation.getter(#onSessionExtend),
        ),
      ) as _i2.Event<_i2.SessionExtend>);

  @override
  _i2.Event<_i2.SessionPing> get onSessionPing => (super.noSuchMethod(
        Invocation.getter(#onSessionPing),
        returnValue: _FakeEvent_6<_i2.SessionPing>(
          this,
          Invocation.getter(#onSessionPing),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionPing>(
          this,
          Invocation.getter(#onSessionPing),
        ),
      ) as _i2.Event<_i2.SessionPing>);

  @override
  _i2.Event<_i2.SessionUpdate> get onSessionUpdate => (super.noSuchMethod(
        Invocation.getter(#onSessionUpdate),
        returnValue: _FakeEvent_6<_i2.SessionUpdate>(
          this,
          Invocation.getter(#onSessionUpdate),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionUpdate>(
          this,
          Invocation.getter(#onSessionUpdate),
        ),
      ) as _i2.Event<_i2.SessionUpdate>);

  @override
  _i2.Event<_i2.SessionDelete> get onSessionDelete => (super.noSuchMethod(
        Invocation.getter(#onSessionDelete),
        returnValue: _FakeEvent_6<_i2.SessionDelete>(
          this,
          Invocation.getter(#onSessionDelete),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionDelete>(
          this,
          Invocation.getter(#onSessionDelete),
        ),
      ) as _i2.Event<_i2.SessionDelete>);

  @override
  _i5.IGenericStore<_i2.ProposalData> get proposals => (super.noSuchMethod(
        Invocation.getter(#proposals),
        returnValue: _FakeIGenericStore_7<_i2.ProposalData>(
          this,
          Invocation.getter(#proposals),
        ),
        returnValueForMissingStub: _FakeIGenericStore_7<_i2.ProposalData>(
          this,
          Invocation.getter(#proposals),
        ),
      ) as _i5.IGenericStore<_i2.ProposalData>);

  @override
  _i2.ISessions get sessions => (super.noSuchMethod(
        Invocation.getter(#sessions),
        returnValue: _FakeISessions_8(
          this,
          Invocation.getter(#sessions),
        ),
        returnValueForMissingStub: _FakeISessions_8(
          this,
          Invocation.getter(#sessions),
        ),
      ) as _i2.ISessions);

  @override
  _i5.IGenericStore<_i2.SessionRequest> get pendingRequests =>
      (super.noSuchMethod(
        Invocation.getter(#pendingRequests),
        returnValue: _FakeIGenericStore_7<_i2.SessionRequest>(
          this,
          Invocation.getter(#pendingRequests),
        ),
        returnValueForMissingStub: _FakeIGenericStore_7<_i2.SessionRequest>(
          this,
          Invocation.getter(#pendingRequests),
        ),
      ) as _i5.IGenericStore<_i2.SessionRequest>);

  @override
  _i2.IPairingStore get pairings => (super.noSuchMethod(
        Invocation.getter(#pairings),
        returnValue: _FakeIPairingStore_9(
          this,
          Invocation.getter(#pairings),
        ),
        returnValueForMissingStub: _FakeIPairingStore_9(
          this,
          Invocation.getter(#pairings),
        ),
      ) as _i2.IPairingStore);

  @override
  _i2.Event<_i2.SessionAuthResponse> get onSessionAuthResponse =>
      (super.noSuchMethod(
        Invocation.getter(#onSessionAuthResponse),
        returnValue: _FakeEvent_6<_i2.SessionAuthResponse>(
          this,
          Invocation.getter(#onSessionAuthResponse),
        ),
        returnValueForMissingStub: _FakeEvent_6<_i2.SessionAuthResponse>(
          this,
          Invocation.getter(#onSessionAuthResponse),
        ),
      ) as _i2.Event<_i2.SessionAuthResponse>);

  @override
  _i5.IGenericStore<_i2.AuthPublicKey> get authKeys => (super.noSuchMethod(
        Invocation.getter(#authKeys),
        returnValue: _FakeIGenericStore_7<_i2.AuthPublicKey>(
          this,
          Invocation.getter(#authKeys),
        ),
        returnValueForMissingStub: _FakeIGenericStore_7<_i2.AuthPublicKey>(
          this,
          Invocation.getter(#authKeys),
        ),
      ) as _i5.IGenericStore<_i2.AuthPublicKey>);

  @override
  _i5.IGenericStore<String> get pairingTopics => (super.noSuchMethod(
        Invocation.getter(#pairingTopics),
        returnValue: _FakeIGenericStore_7<String>(
          this,
          Invocation.getter(#pairingTopics),
        ),
        returnValueForMissingStub: _FakeIGenericStore_7<String>(
          this,
          Invocation.getter(#pairingTopics),
        ),
      ) as _i5.IGenericStore<String>);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.ConnectResponse> connect({
    Map<String, _i2.RequiredNamespace>? requiredNamespaces,
    Map<String, _i2.RequiredNamespace>? optionalNamespaces,
    Map<String, String>? sessionProperties,
    String? pairingTopic,
    List<_i2.Relay>? relays,
    List<List<String>>? methods = const [
      [
        r'wc_sessionPropose',
        r'wc_sessionRequest',
      ]
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #requiredNamespaces: requiredNamespaces,
            #optionalNamespaces: optionalNamespaces,
            #sessionProperties: sessionProperties,
            #pairingTopic: pairingTopic,
            #relays: relays,
            #methods: methods,
          },
        ),
        returnValue:
            _i7.Future<_i2.ConnectResponse>.value(_FakeConnectResponse_10(
          this,
          Invocation.method(
            #connect,
            [],
            {
              #requiredNamespaces: requiredNamespaces,
              #optionalNamespaces: optionalNamespaces,
              #sessionProperties: sessionProperties,
              #pairingTopic: pairingTopic,
              #relays: relays,
              #methods: methods,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.ConnectResponse>.value(_FakeConnectResponse_10(
          this,
          Invocation.method(
            #connect,
            [],
            {
              #requiredNamespaces: requiredNamespaces,
              #optionalNamespaces: optionalNamespaces,
              #sessionProperties: sessionProperties,
              #pairingTopic: pairingTopic,
              #relays: relays,
              #methods: methods,
            },
          ),
        )),
      ) as _i7.Future<_i2.ConnectResponse>);

  @override
  _i7.Future<dynamic> request({
    required String? topic,
    required String? chainId,
    required _i2.SessionRequestParams? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #topic: topic,
            #chainId: chainId,
            #request: request,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<List<dynamic>> requestReadContract({
    required _i2.DeployedContract? deployedContract,
    required String? functionName,
    required String? rpcUrl,
    _i2.EthereumAddress? sender,
    List<dynamic>? parameters = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReadContract,
          [],
          {
            #deployedContract: deployedContract,
            #functionName: functionName,
            #rpcUrl: rpcUrl,
            #sender: sender,
            #parameters: parameters,
          },
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<dynamic> requestWriteContract({
    required String? topic,
    required String? chainId,
    required _i2.DeployedContract? deployedContract,
    required String? functionName,
    required _i2.Transaction? transaction,
    String? method,
    List<dynamic>? parameters = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestWriteContract,
          [],
          {
            #topic: topic,
            #chainId: chainId,
            #deployedContract: deployedContract,
            #functionName: functionName,
            #transaction: transaction,
            #method: method,
            #parameters: parameters,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  void registerEventHandler({
    required String? chainId,
    required String? event,
    void Function(
      String,
      dynamic,
    )? handler,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerEventHandler,
          [],
          {
            #chainId: chainId,
            #event: event,
            #handler: handler,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> ping({required String? topic}) => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
          {#topic: topic},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disconnectSession({
    required String? topic,
    required _i2.ReownSignError? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnectSession,
          [],
          {
            #topic: topic,
            #reason: reason,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, _i2.SessionData> getActiveSessions() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSessions,
          [],
        ),
        returnValue: <String, _i2.SessionData>{},
        returnValueForMissingStub: <String, _i2.SessionData>{},
      ) as Map<String, _i2.SessionData>);

  @override
  Map<String, _i2.SessionData> getSessionsForPairing(
          {required String? pairingTopic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsForPairing,
          [],
          {#pairingTopic: pairingTopic},
        ),
        returnValue: <String, _i2.SessionData>{},
        returnValueForMissingStub: <String, _i2.SessionData>{},
      ) as Map<String, _i2.SessionData>);

  @override
  Map<String, _i2.ProposalData> getPendingSessionProposals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSessionProposals,
          [],
        ),
        returnValue: <String, _i2.ProposalData>{},
        returnValueForMissingStub: <String, _i2.ProposalData>{},
      ) as Map<String, _i2.ProposalData>);

  @override
  _i7.Future<void> dispatchEnvelope(String? url) => (super.noSuchMethod(
        Invocation.method(
          #dispatchEnvelope,
          [url],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> redirectToWallet({
    required String? topic,
    required _i2.Redirect? redirect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redirectToWallet,
          [],
          {
            #topic: topic,
            #redirect: redirect,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.SessionAuthRequestResponse> authenticate({
    required _i2.SessionAuthRequestParams? params,
    String? pairingTopic,
    String? walletUniversalLink,
    List<List<String>>? methods = const [
      [r'wc_sessionAuthenticate']
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #params: params,
            #pairingTopic: pairingTopic,
            #walletUniversalLink: walletUniversalLink,
            #methods: methods,
          },
        ),
        returnValue: _i7.Future<_i2.SessionAuthRequestResponse>.value(
            _FakeSessionAuthRequestResponse_11(
          this,
          Invocation.method(
            #authenticate,
            [],
            {
              #params: params,
              #pairingTopic: pairingTopic,
              #walletUniversalLink: walletUniversalLink,
              #methods: methods,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.SessionAuthRequestResponse>.value(
                _FakeSessionAuthRequestResponse_11(
          this,
          Invocation.method(
            #authenticate,
            [],
            {
              #params: params,
              #pairingTopic: pairingTopic,
              #walletUniversalLink: walletUniversalLink,
              #methods: methods,
            },
          ),
        )),
      ) as _i7.Future<_i2.SessionAuthRequestResponse>);

  @override
  _i7.Future<bool> validateSignedCacao({
    required _i2.Cacao? cacao,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSignedCacao,
          [],
          {
            #cacao: cacao,
            #projectId: projectId,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  String formatAuthMessage({
    required String? iss,
    required _i2.CacaoRequestPayload? cacaoPayload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatAuthMessage,
          [],
          {
            #iss: iss,
            #cacaoPayload: cacaoPayload,
          },
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #formatAuthMessage,
            [],
            {
              #iss: iss,
              #cacaoPayload: cacaoPayload,
            },
          ),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #formatAuthMessage,
            [],
            {
              #iss: iss,
              #cacaoPayload: cacaoPayload,
            },
          ),
        ),
      ) as String);
}
