name: Order Server Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Install Dependencies
        run: go mod tidy
        working-directory: ./initial_order_server

      - name: Build
        run: go build ./...
        working-directory: ./initial_order_server

      - name: Test
        run: go test ./...
        working-directory: ./initial_order_server